<?php

/**
 * @file
 * Implements Drupal hooks for stanford_earth_capx module.
 */

use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\stanford_earth_capx\EarthCapxInfo;
use Drupal\user\Entity\User;

/**
 * Implements hook_entity_delete().
 */
function stanford_earth_capx_entity_delete(EntityInterface $entity) {

  // Only do this for user content.
  if ($entity->bundle() !== 'user') {
    return;
  }

  // Delete record from capx info table.
  EarthCapxInfo::delete($entity->id());

  // Delete record from migration map table.
  $database = \Drupal::database();
  $table = 'migrate_map_earth_capx_importer';
  if ($database->schema()->tableExists($table)) {
    $database->delete($table)
      ->condition('destid1', $entity->id())
      ->execute();
  }

}

/**
 * Implements hook_migrate_prepare_row().
 */
function stanford_earth_capx_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {

  // We need to clean up the phones data from the CAP API since it's an
  // array without keys. This is where we rewrite the array.
  // This hook gets called for every migration so check that it's the CAP-X one.
  if (substr($migration->id(),0,19) === 'earth_capx_importer') {
  //if ($migration->id() === 'earth_capx_importer') {
    $email_test = $row->getSourceProperty("email");
    if (empty($email_test)) {
      $row->setSourceProperty('email', $row->getSourceProperty('sunetid') .
        '@stanford.edu');
    }
    $phones = $row->getSourceProperty('phone');
    $newphones = [];
    if (!empty($phones) && is_array($phones)) {
      $newphones = [];
      foreach ($phones as $ph) {
        $newphones[] = ['phone' => $ph];
      }
    }
    $row->setSourceProperty('phone', $newphones);

    // if the user account already exists, set its id in the row data.
    $sunetid = $row->getSourceProperty('sunetid');
    if (!empty($sunetid)) {

      $sunetuser = user_load_by_name($sunetid);
      if (!empty($sunetuser)) {
        $entityid = intval($sunetuser->id());
        $row->setSourceProperty('uid', $entityid);
        $row->setDestinationProperty('uid', $entityid);
        if (empty($sunetuser->getEmail())) {
          $row->setSourceProperty('updateemail', 1);
        }
      }

      /*
      // update search terms table
      $urls = $row->getSourceProperty('urls');
      if (!empty($urls)) {
        $start = strpos($urls[0],'earthsci:');
        $end = strpos($urls[0],'&');
        $wg = '';
        if ($start !== FALSE && $end !== FALSE) {
          $wg = substr($urls[0], $start, ($end - $start));
        }
        if (!empty($wg)) {
          $properties = [
            'vid' => 'profile_workgroups',
            'name' => $wg,
          ];
          $wg_terms = \Drupal::entityTypeManager()
            ->getStorage('taxonomy_term')
            ->loadByProperties($properties);
          if (!empty($wg_terms)) {
            $entity = reset($wg_terms);
            $search_terms = $entity->field_people_search_terms->getValue();

            $acct_entityid = 0;
            $wg_list = [];
            $search_terms_list = [];
            $db = \Drupal::database();
            $result = $db->query("SELECT * FROM " .
              "{migrate_info_earth_capx_search_terms} WHERE " .
              "sunetid = :sunetid", [':sunetid' => $sunetid]);
            foreach ($result as $record) {
            }
          }
        }
      }
      */
    }
  }
  return TRUE;

}
