<?php
/**
 * @file
 * File description.
 *
 * Long description.
 */

use Drupal\Component\Utility\Unicode;
use Drupal\migrate\Exception\RequirementsException;
use Drupal\migrate\Plugin\RequirementsInterface;
use Drupal\migrate\Plugin\MigrationInterface;
use Drupal\migrate_tools\MigrateExecutable;
use Drupal\migrate\MigrateMessage;
use Drupal\Core\Entity\EntityInterface;
use Drupal\migrate\Row;
use Drupal\migrate\Plugin\MigrateSourceInterface;
use Drupal\stanford_earth_capx\EarthCapxInfo;

/**
 * Implements hook_entity_delete().
 */

function stanford_earth_capx_migrate_prepare_row(Row $row, MigrateSourceInterface $source, MigrationInterface $migration) {
  $info = new EarthCapxInfo($row->getSourceProperty('sunetid'));
  return $info->getOkayToUpdateProfile($row->getSource());
}
